site_name: Unofficial LoongArch Intrinsics Guide
site_url: https://jia.je/unofficial-loongarch-intrinsics-guide
site_description: Unofficial LoongArch Intrinsics Guide
theme:
  name: readthedocs
copyright: Copyright &copy; 2023 Jiajie Chen